# Settings
- defaults:
    link:
      create: true
      relink: true
      force: true # Swap the original file

- clean: ['~']

- link:
    # git
    ~/.gitconfig: gitconfig
    # Zsh    
    ~/.zshrc: zsh/zshrc.zsh
    ~/.zprofile: zsh/zprofile.zsh
    # Brew
    ~/.Brewfile: Brewfile
    # iTerm
    ~/.iTerm/com.googlecode.iterm2.plist:
        path: iTerm/config
        create: true
    # karabiner
    ~/.config/karabiner/karabiner.json:
        path: karabiner/karabiner.json
        create: true
    ~/.config/karabiner.edn:
        path: karabiner/karabiner.edn
        create: true
    # Neovim
    ~/.config/nvim: nvim
