alias ll='exa -la'
alias reload='source ~/.zshrc'
alias ge='ssh -i ~/.ssh/google_compute_engine_yogev_kr  yogev_kr@104.198.243.181'
alias pi='ssh -i ~/.ssh/id_rsa_yogev_kriger pi@192.168.1.20'
alias wifi-pass='wifi-password'
alias d='deactivate'
alias sd='source deactivate'
alias brewski='brew update && brew upgrade && brew cleanup; brew prune; brew doctor'